"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import dynamic from "next/dynamic";
import { configurationError, rpc } from "@/lib/supabase";

const QrScanner = dynamic(() => import("./QrScanner"), { ssr: false });

type Session={session_token:string;expires_at:string;student_id:string;student_no:string;name:string;affiliation?:string|null;role:"user"|"admin";account_status:string;late_count:number};
type Bike={bike_no:string;status:string;station_name?:string|null;location_text?:string|null;model_name?:string|null};
type Rental={active_rental?:boolean;rental_id?:number;bike_no?:string;destination?:string;rented_at?:string;expected_return_at?:string;status?:string;is_late?:boolean;late_minutes?:number};
type Usage={rental_id:number;bike_no:string;destination:string;rented_at:string;expected_return_at:string;returned_at?:string|null;status:string;is_late:boolean;late_minutes:number;return_station?:string|null};
type Fault={fault_id:number;bike_no:string;fault_type:string;description?:string|null;status:string;reported_at:string;resolved_at?:string|null;reporter_student_no?:string|null;reporter_name?:string|null};
type Student={student_no:string;name:string;affiliation?:string|null;role:string;account_status:string;late_count:number;created_at:string};
type AdminBike={bike_no:string;status:string;bike_password:string;station_name?:string|null;model_name?:string|null;note?:string|null;active_rental:boolean;fault_type?:string|null;fault_description?:string|null;fault_reported_at?:string|null};
type AdminUsage=Usage&{student_no:string;student_name:string;affiliation?:string|null};
type AdminStats=Record<string,number>;
type Restriction={restriction_id:number;student_no?:string;student_name?:string;affiliation?:string|null;reason:string;restricted_at:string;released_at?:string|null;release_reason?:string|null;status:string;restricted_by_name?:string|null;released_by_name?:string|null};

const statusLabel:Record<string,string>={available:"대여 가능",rented:"대여 중",fault:"고장",active:"이용 중",overdue:"연체",returned:"반납 완료",restricted:"대여 제한",admin:"관리자",reported:"접수",resolved:"처리 완료"};
const formatDate=(v?:string|null)=>v?new Intl.DateTimeFormat("ko-KR",{dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"-";
const errText=(e:unknown)=>e instanceof Error?e.message:"처리 중 오류가 발생했습니다.";

export default function BicycleRentalApp(){
 const[session,setSession]=useState<Session|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
 useEffect(()=>{const raw=localStorage.getItem("bike_session");if(raw){try{setSession(JSON.parse(raw))}catch{localStorage.removeItem("bike_session")}}},[]);
 const login=async(no:string,name:string)=>{setBusy(true);setMessage("");try{const d=await rpc<Session>("login_student",{p_student_no:no,p_name:name});localStorage.setItem("bike_session",JSON.stringify(d));setSession(d)}catch(e){setMessage(errText(e))}finally{setBusy(false)}};
 const logout=async()=>{if(session){try{await rpc("logout_session",{p_session_token:session.session_token})}catch{}}localStorage.removeItem("bike_session");setSession(null)};
 if(configurationError)return <SetupNotice/>; if(!session)return <Login busy={busy} message={message} onLogin={login}/>;
 return session.role==="admin"?<AdminApp session={session} onLogout={logout}/>:<UserApp session={session} onLogout={logout}/>;
}

function SetupNotice(){return <main className="center-wrap"><section className="card setup"><h1>Supabase 연결값을 입력해 주세요.</h1><pre>NEXT_PUBLIC_SUPABASE_URL=...{"\n"}NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=...</pre></section></main>}
function Login({busy,message,onLogin}:{busy:boolean;message:string;onLogin:(n:string,name:string)=>void}){const[no,setNo]=useState("");const[name,setName]=useState("");return <main className="login-page"><section className="login-hero"><span className="brand-mark">B</span><p className="eyebrow">BICYCLE RENTAL SYSTEM</p><h1>더 간단하고 안전한<br/>자전거 대여 관리</h1><p>학번과 이름으로 로그인하여 자전거를 대여하고 QR로 반납하세요.</p></section><section className="card login-card"><h2>로그인</h2><p className="muted">학번 이름으로 로그인하세요.</p><form className="form-stack" onSubmit={e=>{e.preventDefault();onLogin(no,name)}}><label>학번<input value={no} onChange={e=>setNo(e.target.value)} required/></label><label>이름<input value={name} onChange={e=>setName(e.target.value)} required/></label>{message&&<div className="alert error">{message}</div>}<button className="primary" disabled={busy}>{busy?"로그인 중...":"로그인"}</button></form></section></main>}
function Shell({title,subtitle,name,onLogout,children}:{title:string;subtitle:string;name:string;onLogout:()=>void;children:React.ReactNode}){return <main className="app-shell"><header className="topbar"><div><span className="eyebrow">자전거 대여 관리 시스템</span><h1>{title}</h1><p>{subtitle}</p></div><div className="top-actions"><span className="user-chip">{name}</span><button className="ghost" onClick={onLogout}>로그아웃</button></div></header>{children}<footer>Supabase · Next.js 기반 자전거 대여 시스템</footer></main>}

function UserApp({session,onLogout}:{session:Session;onLogout:()=>void}){
 const token=session.session_token;const[profile,setProfile]=useState<Session>(session);const[tab,setTab]=useState("home");const[rental,setRental]=useState<Rental>({});const[bikes,setBikes]=useState<Bike[]>([]);const[history,setHistory]=useState<Usage[]>([]);const[faults,setFaults]=useState<Fault[]>([]);const[restrictions,setRestrictions]=useState<Restriction[]>([]);const[notice,setNotice]=useState("");const[loading,setLoading]=useState(true);const[returnQr,setReturnQr]=useState("");
 const refresh=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{const[r,b,h,f,rh,p]=await Promise.all([rpc<Rental>("get_current_rental",{p_session_token:token}),rpc<Bike[]>("list_available_bikes",{p_session_token:token}),rpc<Usage[]>("my_usage_history",{p_session_token:token}),rpc<Fault[]>("my_fault_history",{p_session_token:token}),rpc<Restriction[]>("my_restriction_history",{p_session_token:token}),rpc<Session>("my_profile",{p_session_token:token})]);setRental(r||{});setBikes(b||[]);setHistory(h||[]);setFaults(f||[]);setRestrictions(rh||[]);if(p)setProfile({...session,...p,session_token:token,expires_at:session.expires_at})}catch(e){if(!silent)setNotice(errText(e))}finally{if(!silent)setLoading(false)}},[token,session]);
 useEffect(()=>{refresh()},[refresh]);
 useEffect(()=>{if(tab!=="home")return;const timer=window.setInterval(()=>refresh(true),2000);return()=>window.clearInterval(timer)},[tab,refresh]);
 const call=async<T=any>(name:string,params:Record<string,unknown>)=>{setNotice("");try{const r=await rpc<T&{message?:string}>(name,{p_session_token:token,...params});setNotice((r as any)?.message||"처리되었습니다.");await refresh();return r}catch(e){setNotice(errText(e));throw e}};
 const has=Boolean(rental.rental_id);
 return <Shell title={`${session.name}님, 안녕하세요`} subtitle={has?`${rental.bike_no} 자전거를 이용 중입니다.`:"현재 대여 중인 자전거가 없습니다."} name={session.affiliation||session.student_no} onLogout={onLogout}>
  <nav className="tabs user-tabs">{[["home","홈"],["history","이용 내역"],["faultHistory","고장 신고 내역"],["restrictionHistory","대여 제한 내역"]].map(([k,v])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{v}</button>)}</nav>
  {notice&&<div className="alert success">{notice}</div>}{loading?<div className="loading">데이터를 불러오는 중...</div>:<>
   {tab==="home"&&<UserHome session={profile} rental={rental} call={call} setTab={setTab}/>} 
   {tab==="rent"&&<RentPanel bikes={bikes} disabled={has||session.account_status!=="available"} call={call} onDone={()=>setTab("home")}/>} 
   {tab==="return"&&<ReturnScan disabled={!has} onScan={qr=>{setReturnQr(qr);setTab("returnFault")}}/>}
   {tab==="returnFault"&&<ReturnFaultPanel qr={returnQr} bikeNo={rental.bike_no||""} call={call} onDone={()=>{setReturnQr("");setTab("home")}}/>}
   {tab==="history"&&<UsageHistoryPanel history={history}/>} 
   {tab==="faultHistory"&&<FaultHistoryPanel faults={faults}/>} {tab==="restrictionHistory"&&<RestrictionHistoryPanel restrictions={restrictions}/>} 
  </>}
 </Shell>
}

function UserHome({session,rental,call,setTab}:{session:Session;rental:Rental;call:(n:string,p:Record<string,unknown>)=>Promise<any>;setTab:(s:string)=>void}){const[destination,setDestination]=useState("");const[password,setPassword]=useState("");const[passwordLoading,setPasswordLoading]=useState(false);const[passwordError,setPasswordError]=useState("");const has=Boolean(rental.rental_id);const showPassword=async()=>{setPasswordLoading(true);setPasswordError("");setPassword("");try{const d=await rpc<string>("get_current_bike_password_v2",{p_session_token:session.session_token});if(!d)throw new Error("자전거 비밀번호를 불러오지 못했습니다.");setPassword(String(d))}catch(e){setPasswordError(errText(e))}finally{setPasswordLoading(false)}};return <section className="dashboard-grid"><article className="card span-2"><div className="card-head"><div><span className="eyebrow">현재 이용 상태</span><h2>{has?`${rental.bike_no} 대여 중`:"대여 중인 자전거 없음"}</h2></div><span className={`badge ${rental.status||session.account_status}`}>{statusLabel[rental.status||session.account_status]||rental.status||session.account_status}</span></div>{has?<div className="rental-detail"><div><span>목적지</span><b>{rental.destination}</b></div><div><span>반납 예정</span><b>{formatDate(rental.expected_return_at)}</b></div><div><span>연체</span><b>{rental.is_late?`${rental.late_minutes}분`:"아님"}</b></div></div>:<p className="muted">대여 가능한 자전거를 확인하고 이용을 시작하세요.</p>}<div className="button-row">{has?<><button className="primary" type="button" disabled={passwordLoading} onClick={showPassword}>{passwordLoading?"확인 중...":"자전거 비밀번호 확인"}</button><button type="button" onClick={()=>setTab("return")}>QR로 반납</button></>:<button className="primary" type="button" onClick={()=>setTab("rent")}>자전거 대여하기</button>}</div>{passwordError&&<div className="alert error">{passwordError}</div>}{password&&<div className="password-box">자전거 잠금 비밀번호 <strong>{password}</strong></div>}</article><article className="card"><span className="eyebrow">계정 상태</span><h3>{statusLabel[session.account_status]||session.account_status}</h3><p>연체 누적 <b>{session.late_count}회</b></p></article><article className="card"><span className="eyebrow">목적지 변경</span><h3>이동 계획이 바뀌었나요?</h3><form className="inline-form" onSubmit={async e=>{e.preventDefault();await call("change_destination",{p_new_destination:destination});setDestination("")}}><input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="새 목적지" disabled={!has} required/><button disabled={!has}>변경</button></form></article></section>}
function RentPanel({bikes,disabled,call,onDone}:{bikes:Bike[];disabled:boolean;call:(n:string,p:Record<string,unknown>)=>Promise<any>;onDone:()=>void}){const[bikeNo,setBikeNo]=useState("");const[destination,setDestination]=useState("");const[duration,setDuration]=useState(60);return <section className="two-col"><article className="card"><h2>자전거 대여하기</h2><form className="form-stack" onSubmit={async e=>{e.preventDefault();await call("rent_bike",{p_bike_no:bikeNo,p_destination:destination,p_expected_minutes:duration});onDone()}}><label>자전거 번호<select value={bikeNo} onChange={e=>setBikeNo(e.target.value)} required disabled={disabled}><option value="">선택하세요</option>{bikes.map(b=><option key={b.bike_no}>{b.bike_no}</option>)}</select></label><label>목적지<input value={destination} onChange={e=>setDestination(e.target.value)} required disabled={disabled}/></label><label>이용 예정 시간<select value={duration} onChange={e=>setDuration(Number(e.target.value))} disabled={disabled}><option value={0}>10초 (시연용)</option>{Array.from({length:8},(_,i)=><option value={(i+1)*60} key={i+1}>{i+1}시간</option>)}</select></label><button className="primary" disabled={disabled}>대여하기</button></form></article><article className="card"><h2>{bikes.length}대 이용 가능</h2><div className="list">{bikes.map(b=><button type="button" className={`list-item selectable ${bikeNo===b.bike_no?"selected":""}`} key={b.bike_no} onClick={()=>setBikeNo(b.bike_no)}><div><b>{b.bike_no}</b><span>{b.model_name||"자전거"}</span></div><small>{b.station_name||"위치 미지정"}</small></button>)}</div></article></section>}
function ReturnScan({disabled,onScan}:{disabled:boolean;onScan:(qr:string)=>void}){const[scanner,setScanner]=useState(false);return <section className="card narrow"><h2>QR 코드로 반납</h2><p className="muted">대여소에 부착된 QR 코드를 카메라로 스캔하세요.</p><button className="primary" disabled={disabled} onClick={()=>setScanner(v=>!v)}>{scanner?"스캐너 닫기":"카메라로 QR 스캔"}</button>{scanner&&<QrScanner onScan={v=>{setScanner(false);onScan(v)}}/>}</section>}
function ReturnFaultPanel({qr,bikeNo,call,onDone}:{qr:string;bikeNo:string;call:(n:string,p:Record<string,unknown>)=>Promise<any>;onDone:()=>void}){const[choice,setChoice]=useState<""|"none"|"fault">("");const[type,setType]=useState("");const[desc,setDesc]=useState("");return <section className="card narrow return-check-card"><h2>반납 전 자전거 상태 확인</h2><p className="muted">{bikeNo} 자전거의 상태를 직접 선택한 뒤 반납을 완료하세요.</p><form className="form-stack" onSubmit={async e=>{e.preventDefault();if(!choice)return;await call("return_bike_by_station_qr",{p_station_qr:qr,p_has_fault:choice==="fault",p_fault_type:choice==="fault"?type:null,p_fault_description:choice==="fault"?desc:null});onDone()}}><div className="return-choice" role="group" aria-label="자전거 고장 여부"><button type="button" className={choice==="none"?"choice-button active":"choice-button"} onClick={()=>setChoice("none")}>고장 없음</button><button type="button" className={choice==="fault"?"choice-button danger-choice active":"choice-button danger-choice"} onClick={()=>setChoice("fault")}>고장 있음</button></div>{choice==="fault"&&<><label>고장 유형<input value={type} onChange={e=>setType(e.target.value)} placeholder="예: 브레이크, 체인, 타이어" required/></label><label>상세 설명<textarea value={desc} onChange={e=>setDesc(e.target.value)} placeholder="고장 상태를 자세히 입력하세요." required/></label></>}<button className="primary mobile-primary" disabled={!choice}>반납 완료</button></form></section>}
function UsageHistoryPanel({history}:{history:Usage[]}){return <section className="card"><h2>이용 내역</h2>{history.length===0?<div className="empty">아직 이용 내역이 없습니다.</div>:<div className="table-wrap"><table><thead><tr><th>자전거</th><th>목적지</th><th>대여</th><th>반납</th><th>상태</th></tr></thead><tbody>{history.map(x=><tr key={x.rental_id}><td>{x.bike_no}</td><td>{x.destination}</td><td>{formatDate(x.rented_at)}</td><td>{formatDate(x.returned_at)}</td><td>{statusLabel[x.status]||x.status}</td></tr>)}</tbody></table></div>}</section>}
function FaultHistoryPanel({faults}:{faults:Fault[]}){return <section className="card"><h2>고장 신고 내역</h2>{faults.length===0?<div className="empty">반납 시 접수한 고장 신고가 없습니다.</div>:<div className="list">{faults.map(x=><div className="list-item" key={x.fault_id}><div><b>{x.bike_no} · {x.fault_type}</b><span>{x.description||"상세 설명 없음"}</span></div><small>{formatDate(x.reported_at)}</small></div>)}</div>}</section>}

function RestrictionHistoryPanel({restrictions}:{restrictions:Restriction[]}){return <section className="card"><h2>대여 제한 내역</h2>{restrictions.length===0?<div className="empty">대여 제한 내역이 없습니다.</div>:<div className="table-wrap"><table><thead><tr><th>제한 사유</th><th>제한 시각</th><th>해제 시각</th><th>상태</th></tr></thead><tbody>{restrictions.map(x=><tr key={x.restriction_id}><td>{x.reason}</td><td>{formatDate(x.restricted_at)}</td><td>{formatDate(x.released_at)}</td><td>{x.status==="active"?"제한 중":"해제됨"}{x.release_reason&&<small>{x.release_reason}</small>}</td></tr>)}</tbody></table></div>}</section>}

function AdminApp({session,onLogout}:{session:Session;onLogout:()=>void}){const token=session.session_token;const[tab,setTab]=useState("dashboard");const[stats,setStats]=useState<AdminStats>({});const[students,setStudents]=useState<Student[]>([]);const[bikes,setBikes]=useState<AdminBike[]>([]);const[usage,setUsage]=useState<AdminUsage[]>([]);const[faults,setFaults]=useState<Fault[]>([]);const[restrictions,setRestrictions]=useState<Restriction[]>([]);const[notice,setNotice]=useState("");const[loading,setLoading]=useState(true);const refresh=useCallback(async()=>{setLoading(true);try{const[s,st,b,u,f,rh]=await Promise.all([rpc<AdminStats>("admin_dashboard",{p_session_token:token}),rpc<Student[]>("admin_list_students",{p_session_token:token}),rpc<AdminBike[]>("admin_list_bikes",{p_session_token:token}),rpc<AdminUsage[]>("admin_usage_history",{p_session_token:token}),rpc<Fault[]>("admin_fault_history",{p_session_token:token}),rpc<Restriction[]>("admin_restriction_history",{p_session_token:token})]);setStats(s||{});setStudents(st||[]);setBikes(b||[]);setUsage(u||[]);setFaults(f||[]);setRestrictions(rh||[])}catch(e){setNotice(errText(e))}finally{setLoading(false)}},[token]);useEffect(()=>{refresh()},[refresh]);const call=async(n:string,p:Record<string,unknown>)=>{try{const r=await rpc<{message?:string}>(n,{p_session_token:token,...p});setNotice(r.message||"처리되었습니다.");await refresh()}catch(e){setNotice(errText(e))}};return <Shell title="관리자 대시보드" subtitle="자전거, 생도, 대여 및 고장 상태를 관리합니다." name={session.name} onLogout={onLogout}><nav className="tabs admin-tabs">{[["dashboard","현황"],["students","생도 관리"],["bikes","자전거 관리"],["usage","전체 이용 내역"],["faults","전체 고장 내역"],["restrictions","전체 대여 제한 내역"]].map(([k,v])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{v}</button>)}</nav>{notice&&<div className="alert success">{notice}</div>}{loading?<div className="loading">관리 데이터를 불러오는 중...</div>:<>{tab==="dashboard"&&<AdminDashboard stats={stats}/>} {tab==="students"&&<StudentAdmin students={students} call={call}/>} {tab==="bikes"&&<BikeAdmin bikes={bikes} call={call}/>} {tab==="usage"&&<AdminUsagePanel usage={usage}/>} {tab==="faults"&&<AdminFaultPanel faults={faults}/>} {tab==="restrictions"&&<AdminRestrictionPanel restrictions={restrictions}/>}</>}</Shell>}
function AdminDashboard({stats}:{stats:AdminStats}){const labels:Record<string,string>={total_students:"전체 생도",total_bikes:"총 자전거 수",available_bikes:"대여 가능",rented_bikes:"대여 중",fault_bikes:"고장",active_rentals:"정상 대여",overdue_rentals:"연체 대여",restricted_students:"제한 생도"};return <section className="stats-grid">{Object.entries(labels).map(([k,v])=><article className="card stat" key={k}><span>{v}</span><strong>{stats[k]??0}</strong></article>)}</section>}
function StudentAdmin({students,call}:{students:Student[];call:(n:string,p:Record<string,unknown>)=>Promise<void>}){
 const[selected,setSelected]=useState("");
 const[restrictedFirst,setRestrictedFirst]=useState(true);
 const[restrictionReason,setRestrictionReason]=useState("");
 const[releaseReason,setReleaseReason]=useState("");
 const user=students.find(s=>s.student_no===selected);
 const users=students.filter(s=>s.role==="user");
 const sorted=[...users].sort((a,b)=>restrictedFirst?Number(b.account_status==="restricted")-Number(a.account_status==="restricted")||a.student_no.localeCompare(b.student_no):a.student_no.localeCompare(b.student_no));
 const selectStudent=(studentNo:string)=>{setSelected(studentNo);setRestrictionReason("");setReleaseReason("")};
 const restrictStudent=async()=>{
  if(!user||user.account_status==="restricted")return;
  await call("admin_restrict_student",{p_student_no:selected,p_reason:restrictionReason.trim()||"관리자 직접 제한"});
  setRestrictionReason("");
 };
 const releaseRestriction=async()=>{
  if(!user||user.account_status!=="restricted")return;
  await call("admin_release_student_restriction",{p_student_no:selected,p_release_reason:releaseReason.trim()||"관리자 직접 해제"});
  setReleaseReason("");
 };
 return <section className="two-col admin">
  <article className="card">
   <div className="card-head"><h2>생도 목록</h2><label className="check"><input type="checkbox" checked={restrictedFirst} onChange={e=>setRestrictedFirst(e.target.checked)}/>대여 제한 생도 먼저</label></div>
   <div className="list">{sorted.map(s=><button className={`list-item selectable ${selected===s.student_no?"selected":""}`} key={s.student_no} onClick={()=>selectStudent(s.student_no)}><div><b>{s.name} · {s.student_no}</b><span>{s.affiliation||"소속 없음"}</span></div><small>{statusLabel[s.account_status]||s.account_status}<br/>연체 {s.late_count}회</small></button>)}</div>
  </article>
  <article className="card">
   <h2>{user?`${user.name} (${user.student_no})`:"생도를 선택하세요"}</h2>
   {user&&<p className="muted">사유 입력은 선택 사항입니다.</p>}
   {user&&user.account_status!=="restricted"&&<label>대여 제한 사유 (선택)<textarea value={restrictionReason} onChange={e=>setRestrictionReason(e.target.value)} placeholder="필요한 경우 제한 사유를 입력하세요."/></label>}
   {user?.account_status==="restricted"&&<label>제한 해제 사유 (선택)<textarea value={releaseReason} onChange={e=>setReleaseReason(e.target.value)} placeholder="필요한 경우 해제 사유를 입력하세요."/></label>}
   <div className="button-row">
    <button className="danger" disabled={!user||user.account_status==="restricted"} onClick={restrictStudent}>대여 제한</button>
    <button className="primary" disabled={!user||user.account_status!=="restricted"} onClick={releaseRestriction}>제한 해제</button>
   </div>
  </article>
 </section>
}
function BikeAdmin({bikes,call}:{bikes:AdminBike[];call:(n:string,p:Record<string,unknown>)=>Promise<void>}){const[selected,setSelected]=useState("");const[status,setStatus]=useState("available");const[type,setType]=useState("");const[desc,setDesc]=useState("");const[faultFirst,setFaultFirst]=useState(true);const bike=bikes.find(b=>b.bike_no===selected);const sorted=[...bikes].sort((a,b)=>faultFirst?Number(b.status==="fault")-Number(a.status==="fault")||a.bike_no.localeCompare(b.bike_no):a.bike_no.localeCompare(b.bike_no));return <section className="two-col admin"><article className="card"><div className="card-head"><h2>자전거 목록</h2><label className="check"><input type="checkbox" checked={faultFirst} onChange={e=>setFaultFirst(e.target.checked)}/>고장 자전거 먼저</label></div><div className="list">{sorted.map(b=><button className={`list-item selectable ${selected===b.bike_no?"selected":""}`} key={b.bike_no} onClick={()=>{setSelected(b.bike_no);setStatus(b.status==="fault"?"fault":"available");setType("");setDesc("")}}><div><b>{b.bike_no}</b><span>{b.model_name||"자전거"} · {b.station_name||"위치 없음"}</span></div><small><span className={`badge ${b.active_rental?"rented":b.status}`}>{b.active_rental?"대여 중":statusLabel[b.status]||b.status}</span></small></button>)}</div></article><article className="card"><h2>{bike?bike.bike_no:"자전거를 선택하세요"}</h2>{bike&&<><p className="muted">잠금 비밀번호: <b>{bike.bike_password}</b></p>{bike.status==="fault"&&<div className="alert error"><b>고장 유형:</b> {bike.fault_type||"미입력"}<br/><b>상세 설명:</b> {bike.fault_description||"미입력"}<br/><small>{formatDate(bike.fault_reported_at)}</small></div>}{bike.active_rental&&<div className="alert error">대여 중인 자전거는 상태를 수정할 수 없습니다.</div>}</>}<form className="form-stack" onSubmit={async e=>{e.preventDefault();await call("admin_set_bike_status",{p_bike_no:selected,p_status:status,p_note:null,p_fault_type:status==="fault"?type:null,p_fault_description:status==="fault"?desc:null})}}><label>상태<select value={status} onChange={e=>setStatus(e.target.value)} disabled={!bike||bike.active_rental}><option value="available">대여 가능</option><option value="fault">고장</option></select></label>{status==="fault"&&<><label>고장 유형<input value={type} onChange={e=>setType(e.target.value)} required disabled={!bike||bike.active_rental}/></label><label>상세 설명<textarea value={desc} onChange={e=>setDesc(e.target.value)} required disabled={!bike||bike.active_rental}/></label></>}<button className="primary" disabled={!bike||bike.active_rental}>상태 저장</button></form></article></section>}
function AdminUsagePanel({usage}:{usage:AdminUsage[]}){return <section className="card"><h2>대여·반납 내역</h2><div className="table-wrap"><table><thead><tr><th>학생</th><th>자전거</th><th>목적지</th><th>대여</th><th>반납</th><th>상태</th></tr></thead><tbody>{usage.map(x=><tr key={x.rental_id}><td>{x.student_name}<small>{x.student_no}</small></td><td>{x.bike_no}</td><td>{x.destination}</td><td>{formatDate(x.rented_at)}</td><td>{formatDate(x.returned_at)}</td><td>{statusLabel[x.status]||x.status}</td></tr>)}</tbody></table></div></section>}
function AdminFaultPanel({faults}:{faults:Fault[]}){return <section className="card"><h2>전체 고장 내역(누적)</h2><div className="table-wrap"><table><thead><tr><th>자전거</th><th>신고자</th><th>고장 유형</th><th>상세 설명</th><th>접수 시각</th><th>상태</th></tr></thead><tbody>{faults.map(f=><tr key={f.fault_id}><td>{f.bike_no}</td><td>{f.reporter_name||"관리자"}<small>{f.reporter_student_no}</small></td><td>{f.fault_type}</td><td>{f.description||"-"}</td><td>{formatDate(f.reported_at)}</td><td>{statusLabel[f.status]||f.status}</td></tr>)}</tbody></table></div></section>}

function AdminRestrictionPanel({restrictions}:{restrictions:Restriction[]}){return <section className="card"><h2>전체 대여 제한 내역(누적)</h2>{restrictions.length===0?<div className="empty">대여 제한 내역이 없습니다.</div>:<div className="table-wrap"><table><thead><tr><th>생도</th><th>제한 사유</th><th>제한 시각</th><th>해제 시각</th><th>상태</th></tr></thead><tbody>{restrictions.map(x=><tr key={x.restriction_id}><td>{x.student_name}<small>{x.student_no}{x.affiliation?` · ${x.affiliation}`:""}</small></td><td>{x.reason}</td><td>{formatDate(x.restricted_at)}<small>{x.restricted_by_name?`처리: ${x.restricted_by_name}`:""}</small></td><td>{formatDate(x.released_at)}<small>{x.released_by_name?`처리: ${x.released_by_name}`:""}</small></td><td>{x.status==="active"?"제한 중":"해제됨"}{x.release_reason&&<small>{x.release_reason}</small>}</td></tr>)}</tbody></table></div>}</section>}
